### ISSUE TITLE
what the differences between ”asm_hook_create“ and ”hook_create“?when ”asm_hook_create“ will be used? 

### ISSUE THREAD

**Issue by ghost** [nurupo/rootkit#3]

**Comment by nurupo** [comment]
Those are just two different hooking methods.

Assembly hook overwrites the machine code of an existing function to call into our function. It's fun to overwrite function code, but it's not very practical as you can't do so in a single operation. If something calls the function in the middle of you patching it, the whole thing blows up. You can hook any function with this (well, any big enough function, obviously).

The regular hook replaces an existing function pointer with a pointer to our function. This is more practical as you can generally do it in a single atomic operation, though it works only with function pointers.
